require 'rbconfig'
HOST_OS = RbConfig::CONFIG['host_os']
source :rubygems

gem 'rake'

gem 'guard'

case HOST_OS
  when /darwin/i
    gem 'rb-fsevent'
    gem 'growl'
    gem 'guard-pow'
  when /linux/i
    gem 'libnotify'
    gem 'rb-inotify'
  when /mswin|windows/i
    gem 'rb-fchange'
    gem 'win32console'
    gem 'rb-notifu'
end